logging:
  level: INFO
  loggers:
    org.eclipse: WARN
    io.dropwizard: WARN
    com.weinrich.employees: WARN
    org.hibernate: WARN
  appenders:
    - type: console
    - type: file
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/employees.log
      archivedLogFilenamePattern: /tmp/employees-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB


database:
    driverClass: com.mysql.jdbc.Driver
    user: dropwizard
    password: 'password_goes_here'
    url: jdbc:mysql://localhost/employees
    properties:
      hibernate.show_sql: false

server:
    applicationConnectors:
        - type: http
          port: 8080
    adminConnectors:
        - type: http
          port: 8081