logging:
  level: DEBUG
  loggers:
    org.eclipse: ERROR
    io.dropwizard: ERROR
    com.weinrich.employees: ERROR
    org.hibernate: DEBUG
  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/employees.log
      archivedLogFilenamePattern: /tmp/employees-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB


database:
    driverClass: com.mysql.jdbc.Driver
    user: dropwizard
    password: 'P7bU11eVEhqhp'
    url: jdbc:mysql://localhost/employees
    properties:
      hibernate.show_sql: true

server:
    applicationConnectors:
        - type: http
          port: 8080
    adminConnectors:
        - type: http
          port: 8081